version: "4.0"

services:
  dev:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    user: root
    ports: 
      - 3000:3000
      - 9080:9080
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

    mongo:
    image: mongo:6.0.6
